// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Home: typeof import('./../components/Home.vue')['default']
    List: typeof import('./../components/List.vue')['default']
  }
}

export { }
