// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ArrowLeft: typeof import('./../.vitepress/theme/components/icons/ArrowLeft.vue')['default']
    ArrowRight: typeof import('./../.vitepress/theme/components/icons/ArrowRight.vue')['default']
    Card: typeof import('./../.vitepress/theme1/components/Card.vue')['default']
    Comment: typeof import('./../.vitepress/theme1/components/Comment.vue')['default']
    Default: typeof import("./../components/Default.vue")["default"];
    Diary: typeof import('./../.vitepress/theme1/components/Diary.vue')['default']
    Docs: typeof import('./../.vitepress/theme1/components/Docs.vue')['default']
    EditLink: typeof import('./../.vitepress/theme/components/EditLink.vue')['default']
    Friendship: typeof import('./../.vitepress/theme1/components/Friendship.vue')['default']
    Home: typeof import('./../components/Home.vue')['default']
    HomeFooter: typeof import('./../.vitepress/theme/components/HomeFooter.vue')['default']
    LastUpdated: typeof import('./../.vitepress/theme/components/LastUpdated.vue')['default']
    List: typeof import('./../components/List.vue')['default']
    NavBar: typeof import('./../.vitepress/theme/components/NavBar.vue')['default']
    NavBarTitle: typeof import('./../.vitepress/theme/components/NavBarTitle.vue')['default']
    NavDropdownLink: typeof import('./../.vitepress/theme/components/NavDropdownLink.vue')['default']
    NavDropdownLinkItem: typeof import('./../.vitepress/theme/components/NavDropdownLinkItem.vue')['default']
    NavLink: typeof import('./../.vitepress/theme/components/NavLink.vue')['default']
    NavLinks: typeof import('./../.vitepress/theme/components/NavLinks.vue')['default']
    NButton: typeof import("naive-ui")["NButton"];
    NextAndPrevLinks: typeof import('./../.vitepress/theme/components/NextAndPrevLinks.vue')['default']
    OutboundLink: typeof import('./../.vitepress/theme/components/icons/OutboundLink.vue')['default']
    Page: typeof import('./../.vitepress/theme/components/Page.vue')['default']
    PageFooter: typeof import('./../.vitepress/theme/components/PageFooter.vue')['default']
    PageList: typeof import('./../.vitepress/theme/components/PageList.vue')['default']
    Print: typeof import('./../.vitepress/theme1/components/Print.vue')['default']
    SideBar: typeof import('./../.vitepress/theme/components/SideBar.vue')['default']
    SideBarLinks: typeof import('./../.vitepress/theme/components/SideBarLinks.vue')['default']
    Subscribe: typeof import('./../.vitepress/theme1/components/Subscribe.vue')['default']
    Tags: typeof import('./../.vitepress/theme1/components/Tags.vue')['default']
    ToggleSideBarButton: typeof import('./../.vitepress/theme/components/ToggleSideBarButton.vue')['default']
    WebsiteMonitoring: typeof import('./../docs/website-Monitoring.md')['default']
  }
}

export { }
