// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    FluentDarkTheme24Filled: typeof import('~icons/fluent/dark-theme24-filled')['default']
    Home: typeof import('./../components/Home.vue')['default']
    IconAccessibility: typeof import('~icons/ic/on-accessibility')['default']
    List: typeof import('./../components/List.vue')['default']
    MdiAccount: typeof import('~icons/mdi/account')['default']
  }
}

export { }
